### ISSUE TITLE
[SDLRetro][FunKey S] Newer API calls make the app crash

### ISSUE THREAD

**Issue by DrUm78** [soarqin/sdlretro#2]
Hardware: FunKey S (SoC V3s ARM Cortex A7-A clocked @ 1.2GHz)
Software: sdlretro for the frontent (https://github.com/FunKey-Project/sdlretro) and FBNeo 1.0.0.03 for the Libretro core (compiled from last [b7bebfe](https://github.com/libretro/FBNeo/commit/b7bebfe85d22b788a7a7c44c7c0ebd9d410bd445)).

Newer API calls make the app crash without any notice. SDLRetro does not seem to handle them well.

I can't launch any game from FBNeo, even if the CRCs match perfectly the ones in https://github.com/libretro/FBNeo/tree/master/dats. All it does is bringing me back to the desktop (GMenu2X). Windows port works fine with 1.0.0.02 roms (this port has not been released in 1.0.0.03 yet so I can't compare with the exact same romset).

Here is the only error message I get in GMenu2X logs:
[07-05 08:36:26 I] Unhandled env: 0x22
[07-05 08:36:26 I] Unhandled env: 0x3E

Here is the discussion about it: https://github.com/libretro/FBNeo/issues/818

**Comment by soarqin** [comment]
I'll look into this later.
I'm not sure if fbneo uses hw-accel related APIs. SDLRetro does not suppot them well, ppsspp gets crash and I could not find the reason.

**Comment by soarqin** [comment]
Tested x64 build with fbneo from latest RetroArch [here](https://buildbot.libretro.com/nightly/windows/x86_64/latest/), everything's working fine in SDL1 frontend, and blank screen in SDL2 frontend(and I fixed it).
I think FunKey S uses an SDL1 frontend, so this bug does not affect.

As a conclusion, I think there might be other problems for fbneo core running on FunKey S. Perhaps mem not enough, or arm compiler bug.

**Comment by DrUm78** [comment]
Indeed, the FunKey S uses SDL1.2. FBNeo core is 34MB once stripped and the FunKey S has only 64MB of RAM but core like ScummVM (54MB stripped) works fine though. I don't get any fatal error while compiling the core and I can even reach some UI for games that require some extra files like Neo-Geo (but unreadable on the FunKey S 240x240 screen unfortunately).
Anyway thanks for your help, much appreciated.

**Comment by soarqin** [comment]
Static code segments are mmapped into virtual memory which does not use any RAM, only dynamic memory segments are using RAM, so file size of .so's does not make sense for RAM use.

**Comment by DrUm78** [comment]
Ok, just figured out that the culprit was FBNeo core and it has been fixed in this commit: https://github.com/libretro/FBNeo/commit/a8a2a7cecc99c18061851d23acd59fe5a1ddd942.
Discussion here: https://github.com/libretro/FBNeo/issues/818#issuecomment-876333251

Thanks a lot for your help anyway, I close the issue.
